### PR TITLE
uncheck the checkboxes when submitting an answer

### PR DESCRIPTION
**Pull request by violet4**
implemented javascript ports
removed elm package installation stuff from repository
added .gitignore
added jquery (slim minified version) to support unchecking-checkboxes feature
added build.bash

### CODE REVIEW

**Comment by violet4** [comment]
sorry, I know this commit is pretty invasive, but it took a lot of changes to make it work. at least now when subsequent voters vote, they won't get to see the previous peron's answer.

**Comment by violet4** [comment]
and the build method is different now. I created a build.bash file which creates a "main.js" file. in order to view the project, you now need to open index.html in your browser. running elm-reactor or using "elm-make" to build to an html file won't work anymore, because of the javascript porting.

**Comment by MarkeyMarke** [comment]
Hold on, I'm a bit confused here. Aren't you part of the other section's team that is working on Elm? Why are you committing on our project?

**Comment by violet4** [comment]
my teammate asked me to slow down on our project so there's some work left for them to do, but I was having so much fun working on elm that I wanted to keep working on something. I saw that your polling app would allow the next participant to see the previous participant's response, so I wanted to make the checkbox un-check when submitting a vote.

I think we might not even be in the same section of Professor Horstmann's class. I'm in the earlier section.

**Comment by MarkeyMarke** [comment]
That's very nice of you and all, but I can't let this go through unless you get Horstmann's permission. I do not want to risk any form of point deduction.

**Comment by violet4** [comment]
@MarkeyMarke you absolutely do not have to accept my pull request if you don't want to. I did this for myself, but thought the original project owners (you) could benefit.

I learned something important from implementing integration between elm and javascript for the second time, and then while investigating it further, I learned something else:

elm and javascript can't communicate a Model when the Model contains an elm-checked type like your State (we also had the exact same idea of `type State = State1 | State2 | ...` in our project before implementing javascript porting). I converted the state into a String, which feels messy since it's not thoroughly checked by elm, and you'll need an additional "_ -> ..." case in every "case state of" block.

but upon further investigation, I realized that port functions aren't required to take a Model like in the example at https://github.com/evancz/elm-todomvc/blob/master/Todo.elm ; that's just the example they used. I just realized that, while port functions appear to require input, that input could be a Bool rather than a Model (and just give it a dummy boolean value every time you want to send that message)

    -- I thought this was required to take a Model..
    port clearAnswerButtons: Model -> Cmd msg
    -- but this is fine
    port clearAnswerButtons: Bool -> Cmd msg

that makes it safe to keep using the `type State = A|B|...` as you (and we) had before. it just means that, as long as the model contains a type like that, it can't be passed to javascript as a whole, which means you'd need a proxy type for saving/loading in javascript if you wanted to implement browser store. basically a type that was exactly like Model except either had a conversion between the elm type and a javascript-safe type, or a Model without those fields (if those fields aren't all that important)

Because of that, I actually would not accept this pull request (unless it fixed everything I just mentioned and put the State back the way it was before)  (even if your concern wasn't anything class/school/point/grading -related).

I'm going to fix that, and I'll submit a pull request, but again, I'm doing it for my own learning. you absolutely do not have to merge it.

@cayhorstmann

**Comment by violet4** [comment]
didn't mean to submit my newer changes.. I typed my git-push alias by habit....

**Pull request closed without merging**
